<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-09-21 15:26
=======
# Generated by Django 4.2.5 on 2023-09-21 18:01
>>>>>>> 0c0eb59245d79fca6fb1849fc20c0f3c38268a59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('movie', '0002_review'),
=======
        ('movie', '0002_alter_movie_description_review'),
>>>>>>> 0c0eb59245d79fca6fb1849fc20c0f3c38268a59
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='movie/images/default.jpg', upload_to='movie/images/'),
        ),
    ]
